//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reg.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Reg
    {
        [Key]
        public int Cus_Id { get; set; }
        [Required(ErrorMessage = "Name is required.")]
        [Display(Name = "Name : ")]
        public string Cus_Name { get; set; }
        [Display(Name = "Mobile : ")]
        [Required(ErrorMessage = "Mobile Number is required.")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number.")]
        public string Cus_Mobile { get; set; }
        [Display(Name = "Services : ")]
        public string Cus_Services { get; set; }
        [Display(Name = "Company : ")]
        [Required(ErrorMessage = "Company Name is required.")]
        public string Cus_Company { get; set; }
    }
}
